### PR TITLE
fix: Match OPA behavior for split

### LINKED ISSUE #291: Strings::split incompatibility for empty delimiters
OPA and Regorus evaluate split differently when empty delimiters are
used.

In particular, the OPA implementation seems to follow the Go
strings.Split definition ("If sep is empty, Split splits after each
UTF-8 sequence"). In comparison, Regorus uses str::split, which also
returns the beginning and end of the string.

For example:
```
$ opa eval 'split("test", "")'
{
  "result": [
    {
      "expressions": [
        {
          "value": [
            "t",
            "e",
            "s",
            "t"
          ],
          "text": "split(\"test\", \"\")",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

vs.

```
$ regorus eval 'split("test", "")'
{
  "result": [
    {
      "expressions": [
        {
          "value": [
            "",
            "t",
            "e",
            "s",
            "t",
            ""
          ],
          "text": "split(\"test\", \"\")",
          "location": {
            "row": 1,
            "col": 1
          }
        }
      ]
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by anakrish**
In case of empty delimiter, Rust's split returns leading and trailing empty strings whereas Golang's doesn't.
Change behavior to match Golang/OPA.

fixes #291

### CODE REVIEW

File: src/builtins/strings.rs [hunk 1]
```diff
@@ -146,11 +146,32 @@ fn split(span: &Span, params: &[Ref<Expr>], args: &[Value], _strict: bool) -> Re
...
-    ))
+    let mut parts: Vec<Value> = s
+        .split(delimiter.as_ref())
+        .map(|s| Value::String(s.into()))
+        .collect();
+
+    // Handle https://github.com/microsoft/regorus/issues/291
+    // If delimiter is "", rust returns a leading and trailing "", Golang doesn't.
+    if delimiter.as_ref() == "" {
+        if parts.len() >= 2 {
```
Comment (codido) [inline src/builtins/strings.rs]: Any chance this could be simplified, and just set parts to `s.chars().collect()` in this case?

**Review by codido — APPROVED** [review]

File: src/builtins/strings.rs (hunk 1 above)
Comment (anakrish) [reply src/builtins/strings.rs]: Great suggestion. Fixed.
